language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  sonarqube: true
env:
  global:
    secure: "y7ON+eQrJZNOmiEv6q6n3PVL63nnwF4fyNkQ4bedLoCcQkxxKsWBIvbtLZZ9oeMBEzO0Zx9m6tD3kTWXW1Vg5C/Ph2dPJa5kgGXAZeOwQ5abPz5Oxx5ArwOvqOk/BgJnulqNsu1hytJY36+FQgrwZFJsCD57MxOuYlS6hlV2p6XMsV+P/KZrFrMtqfTxXnE0pbg53Gcku/9l+aZaLDFQK4mYRq1G8jMBuGr9heFTlT9n1EXBvGzd2XYR1X6lr3X3gVonT7sp6N/drnP9si/c6iNrhknX03jVJ5Moz7nSdabyoWvJyFwYYPXbBUaEQHT+iG3SIcu6u/VNewARPNpQjMJ33/wlSL/bcoHtrKZYOlTezu6ReINjP9gbMOR3xbklNb0Ps1iQ8NExBcwRXnEwPd5fO6kl05M4XUQLH6oLVw7jbSLSPlheihsXlpp4jRuMCE4r+UR7pwfqNkAmsERO5MqO7VEwffRbhcrX7111Gqu0ROiVifg/dwNZvpOT2Kbd3ZynGRbqxqyXz65zVZ4kBTLRrzUn4zs7KtBBcCCqe9AI7Ro3iKfifKD6PUN+GbvZQgj9NVWNsjcsbkYfW8lXyGA/8UyyVXuPTB2bosQt5EBFstvYMWVr5AMmd+n3yM/6Gn0IGO3nLWlcfbrxBwZZ8jlTm4ixK0WsjEnQpI+MciU="
script:
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
